### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by mmyz88** [UBC-MDS/DSCI532_Group17#24]
Dash App:
- [x] scatter plot - @sunsiche 
- [x] slider bar - @GuanshuTao 
- [x] table ==> dash.table - @mmyz88 
- [x] overall styling - @yuanxiongbear 
- [x] alignment 
- [x] Param explanation - @mmyz88 
- [x]  map - @GuanshuTao 

Docs: 
- [x] Reflection - @GuanshuTao 
- [x] Docstring - @mmyz88 
- [x] Heroku branch auto-deploy - @yuanxiongbear 
- [x] Heroku app reviewer - @yuanxiongbear 
- [x] README enhance - @sunsiche
